@echo off
mkdir src
mkdir src\confusion_detection
mkdir src\confusion_detection\src
mkdir src\repair_policy
mkdir src\repair_policy\src
mkdir src\common
mkdir src\common\src
mkdir models
mkdir models\face_detection
mkdir models\confusion_detection
mkdir config
mkdir scripts
mkdir test
mkdir test\unit
mkdir test\integration
mkdir docs
mkdir docker
