version: '3'

services:
  confusion_detection:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: qtrobot/confusion_detection:latest
    container_name: confusion_detection
    network_mode: host
    privileged: true  # Required for camera access
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # For GUI applications
      - ../logs:/catkin_ws/src/confusion_project/logs  # Mount logs directory
      - /dev:/dev  # For camera access
    devices:
      - /dev/video0:/dev/video0  # Camera device (adjust as needed)
    command: roslaunch confusion_system.launch

  # Optional service for visualization
  rviz:
    image: qtrobot/confusion_detection:latest
    container_name: confusion_detection_rviz
    network_mode: host
    depends_on:
      - confusion_detection
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rosrun rviz rviz -d /catkin_ws/src/confusion_project/config/confusion_system.rviz
